.TH UFW: "8" "January 2008" "" ""

.SH NAME
ufw
.PP
.SH DESCRIPTION
This program is for managing a Linux firewall and aims to provide an easy to
use interface for the user.

.SH USAGE
.TP
ufw [\fB\-\-dry\-run\fR] \fBenable|disable\fR
.TP
ufw [\fB\-\-dry\-run\fR] \fBdefault\fR allow|deny
.TP
ufw [\fB\-\-dry\-run\fR] \fBlogging\fR on|off
.TP
ufw [\fB\-\-dry\-run\fR] \fBstatus\fR
.TP
ufw [\fB\-\-dry\-run\fR] [\fBdelete\fR] \fBallow|deny\fR PORT
.TP
ufw [\fB\-\-dry\-run\fR] \[\fBdelete\fR] fBallow|deny\fR [\fBfrom\fR ADDRESS [PORT]] [\fBto\fR ADDRESS [PORT]]

.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show help message and exit
.TP
\fB\-\-dry\-run\fR
don't modify anything, just show the changes
.TP
\fBenable\fR
reloads firewall and enables firewall on boot
.TP
\fBdisable\fR
unloads firewall and disables firewall on boot
.TP
\fBdefault\fR allow|deny
change the default policy for incoming traffic. Note that existing rules will
have to be migrated manually when changing the default policy.
.TP
\fBlogging\fR on|off
toggle logging
.TP
\fBstatus\fR
show status of firewall
.TP
\fBallow\fR RULE
allow RULE.  See \fBRULE SYNTAX\fR
.TP
\fBdeny\fR RULE
deny RULE.  See \fBRULE SYNTAX\fR
.TP
\fBdelete\fR allow|deny RULE
deletes the corresponding allow/deny RULE

.SH "RULE SYNTAX"
.PP
Users can specify rules using either a simple syntax or a full syntax. The
simple syntax only specifies the port and optionally the protocol to be
allowed or denied on the host. For example:

  ufw allow 53

This rule will allow tcp and udp port 53 to any address on this host. To
specify a protocol, append ':protocol' to the port. For example:

  ufw allow 25:tcp

This will allow tcp port 25 to any address on this host.
.PP
Users can also use a fuller syntax, specifying the source and destination
addresses and ports. For example:

  ufw deny to 80:tcp

This will deny all traffic to tcp port 80 on this host. Another example:

  ufw deny from 10.0.0.0/8 to 192.168.0.1 25:tcp

This will deny all traffic from the RFC1918 Class A network to tcp port 25
with the address 192.168.0.1.
.PP
To delete a rule, simply prefix the original rule with \fBdelete\fR. For
example, if the original rule was:

  ufw deny to 80:tcp

Use this to delete it:

  ufw delete deny to 80:tcp

.SH EXAMPLES
.PP
Deny all access to port 53:

  ufw deny 53

.PP
Allow all access to tcp port 80:

  ufw allow 80:tcp

.PP
Allow all access from RFC1918 networks to this host:

  ufw allow from 10.0.0.0/8
  ufw allow from 172.16.0.0/12
  ufw allow from 192.168.0.0/16

.PP
Deny access to udp port 514 from host 1.2.3.4:

  ufw deny from 1.2.3.4 to 514:udp

.PP
Allow access to udp 1.2.3.4 port 5469 from 1.2.3.5 port 5469:

  ufw allow from 1.2.3.5 5469:udp to 1.2.3.4 5469:udp

.SH NOTES
.PP
Rule ordering is important and the first match wins. Therefore when adding
rules, add the more specific rules first with more general rules later.
.PP
\fBufw\fR is not intended to provide complete firewall functionality via
its command interface, but instead provides an easy way to add or remove
simple rules. It is currently mainly used for host-based firewalls.
.PP
Currently, \fBufw\fR is a front-end for \fBiptables-restore\fR, with its
rules saved in #CONFIG_PREFIX#/ufw/ufw.rules. Administrators can customize
#CONFIG_PREFIX#/ufw/ufw.rules as desired using the standard \fBiptables\fR and
\fBip6tables\fR syntax.
.PP
\fBufw\fR will read in #CONFIG_PREFIX#/ufw/sysctl.conf on boot when enabled.
To change this behavior, modify #CONFIG_PREFIX#/default/ufw.

.SH SEE ALSO
.PP
 \fBiptables\fR(8), \fBip6tables\fR(8), \fBiptables-restore\fR(8), \fBip6tables-restore\fR(8)
\fBsysctl(8)\fR, \fBsysctl.conf(5)\fR

.SH AUTHOR
.PP
ufw is (C) 2008, Canonical Ltd.

.PP
This manual page was originally written by Jamie Strandboge <jamie@ubunty\&.com>
