name: ufw
version: 0.35-0snappy1
architectures: [all]
vendor: Jamie Strandboge <jamie@strandboge.com>
icon: icon.png
services:
  - name: srv
    start: bin/srv
    description: "ufw service"
    caps:
      - network-firewall
binaries:
  - name: cmd
    exec: bin/cli
    description: "ufw command line interface"
    caps:
      - network-firewall
  - name: init
    exec: bin/init
    description: "ufw backend"
    caps:
      - network-firewall
#  - name: shell
#    exec: bin/shell
#    description: "ufw shell"
#    caps:
#      - network-firewall
#      - network-admin
  - name: doc
    exec: bin/doc
    description: "doc viewer"
    caps: []
