#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          ufw
# Required-Start:    mountall.sh
# Required-Stop:     
# Default-Start:     S
# Default-Stop:      
# Short-Description: start firewall
### END INIT INFO

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

[ -x #PREFIX#/sbin/ufw ] || exit 0

. /lib/lsb/init-functions

if [ -s #CONFIG_PREFIX#/default/ufw ]; then
	. #CONFIG_PREFIX#/default/ufw
else
	log_failure_msg "Could not find #CONFIG_PREFIX#/default/ufw (disabling)"
	ENABLED="no"
fi

case "$1" in
start)
	if [ "$ENABLED" = "yes" ] || [ "$ENABLED" = "YES" ]; then
		if [ ! -z "$IPT_SYSCTL" ] && [ -s "$IPT_SYSCTL" ]; then
			log_action_begin_msg "ufw: Loading $IPT_SYSCTL"
			sysctl -q -p $IPT_SYSCTL
			log_action_end_msg $?
		fi
		for m in $IPT_MODULES
		do
			log_action_begin_msg "ufw: Loading $m"
			modprobe $m
			log_action_end_msg $?
		done
		log_action_begin_msg "ufw: Starting firewall"
		#PREFIX#/sbin/ufw enable >/dev/null 2>/dev/null
		log_action_end_msg $?
	else
		log_warning_msg "ufw: Skipping firewall (not enabled)"
	fi
	;;
stop)
	log_warning_msg "ufw: Please use 'ufw disable' to stop"
	;;
restart)
	if [ "$ENABLED" = "yes" ] || [ "$ENABLED" = "YES" ]; then
		log_action_begin_msg "ufw: Restarting firewall"
		#PREFIX#/sbin/ufw disable >/dev/null 2>/dev/null
		#PREFIX#/sbin/ufw enable >/dev/null 2>/dev/null
		log_action_end_msg $?
	else
		log_warning_msg "ufw: Skipping firewall (not enabled)"
	fi
	;;
force-reload)
	log_action_begin_msg "ufw: Forcibly re-loading firewall"
	#PREFIX#/sbin/ufw disable >/dev/null 2>/dev/null
	#PREFIX#/sbin/ufw enable >/dev/null 2>/dev/null
	log_action_end_msg $?
	;;
*)
	echo "Usage: /etc/init.d/ufw {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit 0

