#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          ufw
# Required-Start:    mountall.sh
# Required-Stop:     
# Default-Start:     S
# Default-Stop:      
# Short-Description: start firewall
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

[ -x #PREFIX#/sbin/ufw ] || exit 0

. /lib/lsb/init-functions

if [ -s #CONFIG_PREFIX#/default/ufw ]; then
    . #CONFIG_PREFIX#/default/ufw
else
    log_failure_msg "Could not find #CONFIG_PREFIX#/default/ufw (aborting)"
    exit 1
fi
if [ -s #CONFIG_PREFIX#/ufw/ufw.conf ]; then
    . #CONFIG_PREFIX#/ufw/ufw.conf
else
    log_failure_msg "Could not find #CONFIG_PREFIX#/ufw/ufw.conf (aborting)"
    exit 1
fi

RULES_PATH="#CONFIG_PREFIX#/ufw"
USER_PATH="#STATE_PREFIX#"

case "$1" in
start)
    if iptables -L ufw-user-input -n >/dev/null 2>&1 ; then
        # if firewall loaded, tell to reload instead
        log_warning_msg "Firewall already started, use 'force-reload'"
        exit 0
    fi
    if [ "$ENABLED" = "yes" ] || [ "$ENABLED" = "YES" ]; then
        log_daemon_msg "Starting firewall:" "ufw"
        if [ ! -z "$IPT_SYSCTL" ] && [ -s "$IPT_SYSCTL" ]; then
            log_action_begin_msg "  Loading $IPT_SYSCTL"
            sysctl -q -p $IPT_SYSCTL
            log_action_end_msg $?
        fi
        for m in $IPT_MODULES
        do
            log_action_begin_msg "  Loading $m"
            modprobe $m
            log_action_end_msg $?
        done
        log_action_begin_msg "  Loading rules"

        execs="iptables"
        if [ "$IPV6" = "yes" ] || [ "$IPV6" = "YES" ]; then
            execs="$execs ip6tables"
        fi

        for exe in $execs
        do
            type=""
            if [ "$exe" = "ip6tables" ]; then
                type="6"
            fi
            BEFORE_RULES="$RULES_PATH/before${type}.rules"
            AFTER_RULES="$RULES_PATH/after${type}.rules"
            USER_RULES="$USER_PATH/user${type}.rules"

            # flush the chains
            $exe -F
            $exe -X

            # setup built-in chains' default policy
            $exe -P INPUT $DEFAULT_INPUT_POLICY
            $exe -P OUTPUT $DEFAULT_OUTPUT_POLICY
            $exe -P FORWARD $DEFAULT_FORWARD_POLICY

            # setup some other chains that can be used later
            if [ "$type" != "6" ]; then
                $exe -N ufw${type}-not-local
            fi

            # setup ufw${type}-before-* chains
            $exe -N ufw${type}-before-input
            $exe -N ufw${type}-before-output
            $exe -N ufw${type}-before-forward
            $exe -A INPUT -j ufw${type}-before-input
            $exe -A OUTPUT -j ufw${type}-before-output
            $exe -A FORWARD -j ufw${type}-before-forward
            if [ -s "$RULES_PATH" ]; then
                if ! $exe-restore -n < $BEFORE_RULES ; then
                    log_warning_msg "   Problem running '$BEFORE_RULES'"
                    error="yes"
                fi
            else
                log_warning_msg "   Couldn't find '$BEFORE_RULES'"
            fi

            # setup ufw${type}-user chain
            if [ -s "$USER_PATH" ]; then
                $exe -N ufw${type}-user-input
                $exe -N ufw${type}-user-output
                $exe -N ufw${type}-user-forward
                $exe -A ufw${type}-before-input -j ufw${type}-user-input
                $exe -A ufw${type}-before-output -j ufw${type}-user-output
                $exe -A ufw${type}-before-forward -j ufw${type}-user-forward
                if ! $exe-restore -n < $USER_RULES ; then
                    log_warning_msg "   Problem running '$USER_RULES'"
                    error="yes"
                fi
                # don't include the RETURN lines here, as they will
                # be in the USER_PATH file
            fi

            # now return from the chain
            $exe -A ufw${type}-before-input -j RETURN
            $exe -A ufw${type}-before-output -j RETURN
            $exe -A ufw${type}-before-forward -j RETURN
        
            # setup ufw${type}-after-* chains
            $exe -N ufw${type}-after-input
            $exe -N ufw${type}-after-output
            $exe -N ufw${type}-after-forward
            $exe -A INPUT -j ufw${type}-after-input
            $exe -A OUTPUT -j ufw${type}-after-output
            $exe -A FORWARD -j ufw${type}-after-forward
            if [ -s "$AFTER_RULES" ]; then
                if ! $exe-restore -n < $AFTER_RULES ; then
                    log_warning_msg "   Problem running '$AFTER_RULES'"
                    error="yes"
                fi
            else
                log_warning_msg "    Couldn't find '$AFTER_RULES'"
            fi
            $exe -A ufw${type}-after-input -j RETURN
            $exe -A ufw${type}-after-output -j RETURN
            $exe -A ufw${type}-after-forward -j RETURN
        done

        if [ "$error" = "yes" ]; then
            log_action_end_msg 1
            log_failure_msg "   Error(s) in starting firewall"
            exit 1
        else
            log_action_end_msg 0
        fi
    else
        log_warning_msg "    Skipping firewall (not enabled)"
    fi
    ;;
stop)
    log_action_begin_msg "Stopping firewall"
    error=""
    for exe in iptables ip6tables
    do
        $exe -F || error="yes"
        $exe -X || error="yes"
        $exe -P INPUT ACCEPT || error="yes"
        $exe -P OUTPUT ACCEPT || error="yes"
        $exe -P FORWARD ACCEPT || error="yes"
    done
    if [ "$error" = "yes" ]; then
        log_action_end_msg 1
        exit 1
    else
        log_action_end_msg 0
    fi
    ;;
restart|force-reload)
    if [ "$ENABLED" = "yes" ] || [ "$ENABLED" = "YES" ]; then
        $0 stop
        $0 start
    else
        log_warning_msg "Skipping $1 (not enabled)"
    fi
    ;;
*)
    echo "Usage: /etc/init.d/ufw {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0

