#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          ufw
# Required-Start:    mountall.sh
# Required-Stop:     
# Default-Start:     S
# Default-Stop:      
# Short-Description: start firewall
### END INIT INFO

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

[ -x #PREFIX#/sbin/ufw ] || exit 0

. /lib/lsb/init-functions

if [ -s #CONFIG_PREFIX#/default/ufw ]; then
	. #CONFIG_PREFIX#/default/ufw
else
	log_failure_msg "Could not find #CONFIG_PREFIX#/default/ufw (disabling)"
	ENABLED="no"
fi

case "$1" in
start)
	if [ "$ENABLED" = "yes" ] || [ "$ENABLED" = "YES" ]; then
		if [ ! -z "$SYSCTL" ] && [ -s "$SYSCTL" ]; then
			log_action_begin_msg "Loading $SYSCTL"
			sysctl -q -p $SYSCTL
			log_action_end_msg $?
		fi
		log_action_begin_msg "Starting firewall"
		#PREFIX#/sbin/ufw enable >/dev/null 2>/dev/null
		log_action_end_msg $?
	else
		log_warning_msg "Skipping firewall (not enabled)"
	fi
	;;
stop)
	log_warning_msg "Please use 'ufw disable' to stop"
	;;
restart)
	if [ "$ENABLED" = "yes" ] || [ "$ENABLED" = "YES" ]; then
		log_action_begin_msg "Restarting firewall"
		#PREFIX#/sbin/ufw disable >/dev/null 2>/dev/null
		#PREFIX#/sbin/ufw enable >/dev/null 2>/dev/null
		log_action_end_msg $?
	else
		log_warning_msg "Skipping firewall (not enabled)"
	fi
	;;
force-reload)
	log_action_begin_msg "Forcibly re-loading firewall"
	#PREFIX#/sbin/ufw disable >/dev/null 2>/dev/null
	#PREFIX#/sbin/ufw enable >/dev/null 2>/dev/null
	log_action_end_msg $?
	;;
*)
	echo "Usage: /etc/init.d/ufw {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit 0

