#!/bin/sh -e

case "$1" in
    remove)
        ;;

    purge)
        if [ -e /usr/share/debconf/confmodule ]; then
		. /usr/share/debconf/confmodule
		db_purge
	fi
        update-rc.d ufw remove > /dev/null
        rm -f /etc/ufw/ufw.rules
        rm -f /etc/ufw/before.rules
        rm -f /etc/ufw/before6.rules
        rm -f /etc/ufw/after.rules
        rm -f /etc/ufw/after6.rules
        rm -f /var/lib/ufw/user.rules
        rm -f /var/lib/ufw/user6.rules
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
