#!/bin/sh -e

case "$1" in
    remove)
        ;;

    purge)
        if [ -e /usr/share/debconf/confmodule ]; then
		. /usr/share/debconf/confmodule
		db_purge
	fi
        update-rc.d ufw remove > /dev/null

        for f in before.rules before6.rules after.rules after6.rules
        do
            if which ucf > /dev/null 2>&1; then
                ucf -p /etc/ufw/$f
            fi
            rm -f /etc/ufw/$f
        done
        rm -f /etc/ufw/ufw.rules
        rm -f /var/lib/ufw/user.rules
        rm -f /var/lib/ufw/user6.rules
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
