#! /usr/bin/env python
#
# ufw: front-end for Linux firewalling (cli)
#
# Copyright (C) 2008 Canonical Ltd.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3,
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
import re
import sys

import ufw.frontend
from ufw.common import UFWError
from ufw.util import error

import gettext
gettext.install(ufw.common.programName)

version = "#VERSION#"

# Internationalization
gettext.bindtextdomain(ufw.common.programName, \
                       os.path.join(ufw.common.state_dir, 'messages'))
gettext.textdomain(ufw.common.programName)
_ = gettext.gettext

if sys.version_info[0] < 2 or \
   (sys.version_info[0] == 2 and sys.version_info[1] < 5):
    print >> sys.stderr, ufw.common.programName + \
             _(": Need at least python 2.5)\n")
    sys.exit(1)

if __name__ == "__main__":
    action = ""
    rule = ""
    dryrun = False
    try:
        (action, rule, ip_version, dryrun) = \
            ufw.frontend.process_args(sys.argv)
    except UFWError, e:
        error(e.value)

    if action == "help" or action == "--help":
        ufw.frontend.print_help()
        sys.exit(0)
    elif action == "version" or action == "--version":
        print ufw.common.programName + " " + version
        print "Copyright (C) 2008 Canonical Ltd."
        sys.exit(0)

    try:
        ufw = ufw.frontend.UFWFrontend(dryrun)
    except UFWError, e:
        error(e.value)
    except Exception:
        raise

    try:
        ufw.do_action(action, rule, ip_version)
    except UFWError, e:
        error(e.value)
    except Exception:
        raise

    sys.exit(0)

