#!/bin/sh -e

# ufw-init: helper script to be used by ufw itself
#
# Copyright (C) 2008 Canonical Ltd.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3,
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ -s "#PREFIX#/share/ufw/ufw-init-functions" ]; then
    . "#PREFIX#/share/ufw/ufw-init-functions"
else
    echo "Could not find $s (aborting)"
    exit 1
fi

case "$1" in
start)
    # process multiple error strings
    ret=0
    output=`ufw_start` || ret="$?"
    echo "$output" | while read line ; do
        echo "$line"
    done
    exit "$ret"
    ;;
stop)
    ufw_stop || exit "$?"
    ;;
force-stop)
    ufw_stop --force || exit "$?"
    ;;
restart|force-reload)
    ufw_reload || exit "$?"
    ;;
status)
    ufw_status || exit "$?"
    ;;
flush-all)
    # Use sparingly. It flushes the built-in chains, deletes all non-builtin
    # chains and resets the policy to ACCEPT
    error=""
    execs="iptables"
    if ip6tables -L INPUT >/dev/null 2>&1; then
        execs="$execs ip6tables"
    fi

    for exe in $execs
    do
        $exe -F || error="yes"
        $exe -X || error="yes"
        $exe -P INPUT ACCEPT || error="yes"
        $exe -P OUTPUT ACCEPT || error="yes"
        $exe -P FORWARD ACCEPT || error="yes"
    done
    if [ "$error" = "yes" ]; then
        return 1
    fi
    return 0
    ;;
*)
    echo "Usage: /etc/init.d/ufw {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

