#!/bin/sh -e

# ufw-init: helper script to be used by ufw itself
#
# Copyright (C) 2008 Canonical Ltd.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3,
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ -s "#PREFIX#/share/ufw/ufw-init-functions" ]; then
    . "#PREFIX#/share/ufw/ufw-init-functions"
else
    echo "Could not find $s (aborting)"
    exit 1
fi

case "$1" in
start)
    # process multiple error strings
    ret=0
    output=`ufw_start` || ret="$?"
    echo "$output" | while read line ; do
        echo "$line"
    done
    exit "$ret"
    ;;
stop)
    ufw_stop || exit "$?"
    ;;
force-stop)
    ufw_stop --force || exit "$?"
    ;;
restart|force-reload)
    ufw_reload || exit "$?"
    ;;
status)
    ufw_status || exit "$?"
    ;;
*)
    echo "Usage: /etc/init.d/ufw {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

