#!/bin/sh
set -e

if [ -z "$SNAP" ]; then
    echo "SNAP not set"
    exit 1
fi

PYCACHE="$SNAP_DATA/usr/lib/python3/dist-packages/ufw/__pycache__"
test -d "$PYCACHE" || mkdir -p "$PYCACHE" 2>/dev/null || true

dir=$(dirname "$0")
exec "$dir/connect-plug-firewall-control"
